var startscriptCircles = "CODE:"; 
startscriptCircles += "SET !ERRORIGNORE YES" + "\n";
startscriptCircles += "SET !TIMEOUT_TAG 1" + "\n";
startscriptCircles += "SET !TIMEOUT_STEP 1" + "\n";
startscriptCircles += "SET !TIMEOUT_PAGE 30" + "\n";
startscriptCircles += "SET !TIMEOUT_MACRO 150" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "URL GOTO=http://addmefast.com" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "TAG POS=1 TYPE=A ATTR=TXT:Google<SP>Circles" + "\n";
startscriptCircles += "TAG POS=1 TYPE=DIV ATTR=TXT:Add<SP>to<SP>circles" + "\n";
startscriptCircles += "TAB T=2 " + "\n";
startscriptCircles += "WAIT SECONDS=2 " + "\n";
startscriptCircles += "EVENT TYPE=MOUSEDOWN SELECTOR=\"HTML>BODY>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV:nth-of-type(2)>DIV:nth-of-type(4)>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV:nth-of-type(3)>DIV>DIV>DIV>DIV>DIV>SPAN\" BUTTON=0" + "\n";
startscriptCircles += "EVENT TYPE=MOUSEDOWN SELECTOR=\"HTML>BODY>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV:nth-of-type(2)>DIV:nth-of-type(4)>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV>DIV>DIV>DIV:nth-of-type(2)>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV>DIV>DIV>DIV>DIV>SPAN\" BUTTON=0" + "\n";
startscriptCircles += "WAIT SECONDS=2" + "\n";
startscriptCircles += "TAG POS=1 TYPE=SPAN ATTR=TXT:Following" + "\n";
startscriptCircles += "WAIT SECONDS=2" + "\n";
startscriptCircles += "TAG POS=1 TYPE=SPAN ATTR=TXT:Friends" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "WAIT SECONDS=3" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "WAIT SECONDS=5" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "TAG POS=1 TYPE=A ATTR=TXT:Google<SP>Circles" + "\n";
startscriptCircles += "TAG POS=1 TYPE=DIV ATTR=TXT:Add<SP>to<SP>circles" + "\n";
startscriptCircles += "TAB T=2 " + "\n";
startscriptCircles += "WAIT SECONDS=2 " + "\n";
startscriptCircles += "EVENT TYPE=MOUSEDOWN SELECTOR=\"HTML>BODY>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV:nth-of-type(2)>DIV:nth-of-type(4)>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV:nth-of-type(3)>DIV>DIV>DIV>DIV>DIV>SPAN\" BUTTON=0" + "\n";
startscriptCircles += "EVENT TYPE=MOUSEDOWN SELECTOR=\"HTML>BODY>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV:nth-of-type(2)>DIV:nth-of-type(4)>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV>DIV>DIV>DIV:nth-of-type(2)>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV>DIV>DIV>DIV>DIV>SPAN\" BUTTON=0" + "\n";
startscriptCircles += "WAIT SECONDS=2" + "\n";
startscriptCircles += "TAG POS=1 TYPE=SPAN ATTR=TXT:Following" + "\n";
startscriptCircles += "WAIT SECONDS=2" + "\n";
startscriptCircles += "TAG POS=1 TYPE=SPAN ATTR=TXT:Friends" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "WAIT SECONDS=3" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "WAIT SECONDS=5" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "TAG POS=1 TYPE=A ATTR=TXT:Google<SP>Circles" + "\n";
startscriptCircles += "TAG POS=1 TYPE=DIV ATTR=TXT:Add<SP>to<SP>circles" + "\n";
startscriptCircles += "TAB T=2 " + "\n";
startscriptCircles += "WAIT SECONDS=2 " + "\n";
startscriptCircles += "EVENT TYPE=MOUSEDOWN SELECTOR=\"HTML>BODY>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV:nth-of-type(2)>DIV:nth-of-type(4)>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV:nth-of-type(3)>DIV>DIV>DIV>DIV>DIV>SPAN\" BUTTON=0" + "\n";
startscriptCircles += "EVENT TYPE=MOUSEDOWN SELECTOR=\"HTML>BODY>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV:nth-of-type(2)>DIV:nth-of-type(4)>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV>DIV>DIV>DIV:nth-of-type(2)>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV>DIV>DIV>DIV>DIV>SPAN\" BUTTON=0" + "\n";
startscriptCircles += "WAIT SECONDS=2" + "\n";
startscriptCircles += "TAG POS=1 TYPE=SPAN ATTR=TXT:Following" + "\n";
startscriptCircles += "WAIT SECONDS=2" + "\n";
startscriptCircles += "TAG POS=1 TYPE=SPAN ATTR=TXT:Friends" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "WAIT SECONDS=3" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "WAIT SECONDS=5" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "TAG POS=1 TYPE=A ATTR=TXT:Google<SP>Circles" + "\n";
startscriptCircles += "TAG POS=1 TYPE=DIV ATTR=TXT:Add<SP>to<SP>circles" + "\n";
startscriptCircles += "TAB T=2 " + "\n";
startscriptCircles += "WAIT SECONDS=2 " + "\n";
startscriptCircles += "EVENT TYPE=MOUSEDOWN SELECTOR=\"HTML>BODY>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV:nth-of-type(2)>DIV:nth-of-type(4)>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV:nth-of-type(3)>DIV>DIV>DIV>DIV>DIV>SPAN\" BUTTON=0" + "\n";
startscriptCircles += "EVENT TYPE=MOUSEDOWN SELECTOR=\"HTML>BODY>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV:nth-of-type(2)>DIV:nth-of-type(4)>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV>DIV>DIV>DIV:nth-of-type(2)>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV>DIV>DIV>DIV>DIV>SPAN\" BUTTON=0" + "\n";
startscriptCircles += "WAIT SECONDS=2" + "\n";
startscriptCircles += "TAG POS=1 TYPE=SPAN ATTR=TXT:Following" + "\n";
startscriptCircles += "WAIT SECONDS=2" + "\n";
startscriptCircles += "TAG POS=1 TYPE=SPAN ATTR=TXT:Friends" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "WAIT SECONDS=3" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "WAIT SECONDS=5" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "TAG POS=1 TYPE=A ATTR=TXT:Google<SP>Circles" + "\n";
startscriptCircles += "TAG POS=1 TYPE=DIV ATTR=TXT:Add<SP>to<SP>circles" + "\n";
startscriptCircles += "TAB T=2 " + "\n";
startscriptCircles += "WAIT SECONDS=2 " + "\n";
startscriptCircles += "EVENT TYPE=MOUSEDOWN SELECTOR=\"HTML>BODY>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV:nth-of-type(2)>DIV:nth-of-type(4)>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV:nth-of-type(3)>DIV>DIV>DIV>DIV>DIV>SPAN\" BUTTON=0" + "\n";
startscriptCircles += "EVENT TYPE=MOUSEDOWN SELECTOR=\"HTML>BODY>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV:nth-of-type(2)>DIV:nth-of-type(4)>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV>DIV>DIV>DIV:nth-of-type(2)>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV>DIV>DIV>DIV>DIV>SPAN\" BUTTON=0" + "\n";
startscriptCircles += "WAIT SECONDS=2" + "\n";
startscriptCircles += "TAG POS=1 TYPE=SPAN ATTR=TXT:Following" + "\n";
startscriptCircles += "WAIT SECONDS=2" + "\n";
startscriptCircles += "TAG POS=1 TYPE=SPAN ATTR=TXT:Friends" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "WAIT SECONDS=3" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "WAIT SECONDS=5" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "TAG POS=1 TYPE=A ATTR=TXT:Google<SP>Circles" + "\n";
startscriptCircles += "TAG POS=1 TYPE=DIV ATTR=TXT:Add<SP>to<SP>circles" + "\n";
startscriptCircles += "TAB T=2 " + "\n";
startscriptCircles += "WAIT SECONDS=2 " + "\n";
startscriptCircles += "EVENT TYPE=MOUSEDOWN SELECTOR=\"HTML>BODY>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV:nth-of-type(2)>DIV:nth-of-type(4)>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV:nth-of-type(3)>DIV>DIV>DIV>DIV>DIV>SPAN\" BUTTON=0" + "\n";
startscriptCircles += "EVENT TYPE=MOUSEDOWN SELECTOR=\"HTML>BODY>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV:nth-of-type(2)>DIV:nth-of-type(4)>DIV>DIV>DIV:nth-of-type(2)>DIV>DIV>DIV>DIV>DIV:nth-of-type(2)>DIV:nth-of-type(2)>DIV:nth-of-type(3)>DIV>DIV>DIV>DIV>DIV>SPAN\" BUTTON=0" + "\n";
startscriptCircles += "WAIT SECONDS=2" + "\n";
startscriptCircles += "TAG POS=1 TYPE=SPAN ATTR=TXT:Following" + "\n";
startscriptCircles += "WAIT SECONDS=2" + "\n";
startscriptCircles += "TAG POS=1 TYPE=SPAN ATTR=TXT:Friends" + "\n";
startscriptCircles += "TAB T=1" + "\n";
startscriptCircles += "WAIT SECONDS=3" + "\n";
startscriptCircles += "TAB CLOSEALLOTHERS" + "\n";
startscriptCircles += "WAIT SECONDS=5" + "\n";
startscriptCircles += "REFRESH" + "\n";
var i=0;
for (i=1; i <= 9999; i++)
{
	iimPlay(startscriptCircles,25);
	iimDisplay("Current loop is: "+ i);
}