var macroStartTW;
macroStartTW ="CODE:"+"\n";
macroStartTW +="SET !ERRORIGNORE YES" + "\n"+"\n";
macroStartTW+="VERSION BUILD=8300326 RECORDER=FX"+"\n"+"\n";
macroStartTW+="SET !ERRORIGNORE YES"+"\n"+"\n";
macroStartTW+="SET !TIMEOUT_TAG 1"+"\n"+"\n";
macroStartTW+="SET !TIMEOUT_STEP 1"+"\n"+"\n";
macroStartTW+="SET !TIMEOUT_PAGE 30"+"\n"+"\n";
macroStartTW+="SET !REPLAYSPEED FAST"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=A ATTR=TXT:Twitter<SP>Followers"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=DIV ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="FRAME F=0"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=BUTTON ATTR=TXT:Follow"+"\n"+"\n";
macroStartTW+="TAB T=2"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=B ATTR=TXT:Risposta"+"\n"+"\n";
macroStartTW+="SET !EXTRACT NULL"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status EXTRACT=TXT"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=TEXTAREA FORM=ID:update-form ATTR=ID:status CONTENT="+Math.round(Math.random()*10001)+"<SP>{{!EXTRACT}}<SP>https://www.youtube.com/watch?v=4gybPf7e_fg"+"\n"+"\n";
macroStartTW+="TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:update-form ATTR=*"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=2"+"\n"+"\n";
macroStartTW+="TAB T=1"+"\n"+"\n";
macroStartTW+="TAB CLOSEALLOTHERS"+"\n"+"\n";
macroStartTW+="WAIT SECONDS=5"+"\n"+"\n";


var i=0;
var n=99999;

for (i=1; i <= n; i++)
{
iimPlay("CODE:"+"URL GOTO=www.addmefast.com")


iimPlay(macroStartTW,25)

iimDisplay("Current loop is: "+i)

iimDisplay("New Page")

}



